

compass_english2tradtional_chinese = {"Yellow Plants": "你地圖中的豐收含有至少 1 個黃色作物",
                                      "Mirror of Delirium": "你的地圖有 1 個譫妄之鏡",
                                      "Beyond": "擊殺敵人將會吸引更強大的怪物登場",
                                      "Blue Plants": "你地圖中的豐收含有至少 1 個藍色作物",
                                      "Purple Plants": "你地圖中的豐收含有至少 1 個紫色作物",
                                      "Sacred Grove": "你的地圖含有聖殿密園",
                                      "8 Modifiers": "你地圖中掉落的地圖為有 8 個詞綴的已汙染地圖",
                                      "Conqueror Map": "完成你的地圖 (階級 14+) 時，掉落 1 個額外征服者地圖",
                                      "Abyss": "你的地圖含有 1 個額外深淵",
                                      "Shaper Guardian": "完成你的地圖 (階級 14+) 時，掉落 1 個額外塑界者守護者地圖",
                                      "Alva": "你的地圖含有艾瓦",
                                      "Copy of Beasts": "在你的地圖製造已捕捉野獸的複製體",
                                      "Chayula": "你地圖中的裂痕為夏烏拉",
                                      "Strongbox Enraged": "保險箱的怪物受到激怒效果影響",
                                      "Delirium Reward": "你地圖中譫妄獎勵條加速 100% 填滿",
                                      "Elder Guardian": "完成你的地圖 (階級 14+) 時，掉落 1 個額外尊師守護者地圖",
                                      "Legion": "你的地圖含有 1 個額外戰亂事件",
                                      "Magic Pack Size": "增加 25% 魔法怪物群大小",
                                      "Mysterious Harbinger": "地圖頭目身旁有神祕的神諭",
                                      "Oils Tier": "你地圖掉落的油瓶高 1 階",
                                      "Splinters Emblems Duplicate": "你地圖中戰亂怪物掉落的裂片和徽印被複製",
                                      "Uul-Netol": "你地圖中的裂痕為烏爾尼多",
                                      "Contracts Implicit": "你地圖中掉落的非傳奇劫盜契約書有 1 個額外固定詞綴",
                                      "Gloom Shrine": "你的地圖含有 1 個額外漆黑神殿",
                                      "Jun": "你的地圖含有瓊恩",
                                      "Map 20% Quality": "你地圖有 20% 品質",
                                      "Runic Monster Markers": "你的地圖增加 100% 符文怪物印記的數量",
                                      "Syndicate Intelligence": "增加 100% 你地圖中永生密教目標事件獲取的情報",
                                      "Unidentified Map": "未鑑定地圖的怪物群大小",
                                      "Alluring": "你的地圖吸引人",
                                      "Breach": "你的地圖含有額外 1 個裂痕",
                                      "Gilded Scarab": "最初 3 個被附身的怪物掉落 1 個額外鍍金聖甲蟲",
                                      "Ritual Altars": "你的地圖含有祭祀神壇",
                                      "Strongbox Corrupted": "你的地圖內的保險箱已汙染",
                                      "Bodyguards": "完成此你的地圖時額外掉落 1 張地圖",
                                      "Smuggler's Cache": "區域含有 1 個走私者的祕寶",
                                      "Soul Gain Prevention": "玩家的瓦爾技能不套用停止獲得靈魂",
                                      "Lightning Monsters": "你的地圖含有額外 6 群造成閃電傷害的怪物",
                                      "Blight": "你的地圖含有 1 個凋落事件",
                                      "Boss Drop Unique": "地圖頭目掉落 1 個額外傳奇物品",
                                      "Chaos Monsters": "你的地圖含有額外 6 群造成混沌傷害的怪物",
                                      "Cold Monsters": "你的地圖含有額外 6 群造成冰冷傷害的怪物",
                                      "Convert Monsters": "你的地圖含有額外 6 群被擊殺時會轉化的怪物",
                                      "Einhar": "你的地圖含有埃哈",
                                      "Esh": "你地圖中的裂痕為艾許",
                                      "Essence": "你的地圖含有 1 個額外精髓",
                                      "Fire Monsters": "你的地圖含有額外 6 群造成火焰傷害的怪物",
                                      "Hunted Traitors": "你的地圖含有許多背叛者",
                                      "Map Quality to Rarity": "你地圖的品質加成同時套用至掉落物品的稀有度",
                                      "Mortal/Sacrifice Fragment": "每個使用的奉獻碎片，使你的地圖有 50% 機率含有奉獻之贈",
                                      "Niko": "你的地圖含有尼科",
                                      "Rare Map Rare Packs": "你的魔法地圖含有 4 群額外魔法怪物",
                                      "Reflected": "玩家和他們的召喚物不能承受反射傷害",
                                      "Resonating Shrine": "你的地圖含有 1 個額外共振神殿",
                                      "Rogue Exiles": "你的地圖含有額外 2 個盜賊流亡者",
                                      "Tormented Heretic": "最初 3 個被附身的怪物掉落 1 個額外地圖",
                                      "Tul": "你地圖中的裂痕為托沃",
                                      "Vaal Monsters Items Corrupted": "你的地圖內已汙染瓦爾怪物掉落物品，有 25% 機率為已汙染",
                                      "Xoph": "你地圖中的裂痕為索伏",
                                      "Boss Drop Vaal": "你已汙染地圖的地圖頭目掉落 2 個額外瓦爾物品",
                                      "Flasks Instant": "玩家透過藥劑立刻恢復生命和魔力",
                                      "Mysterious Barrels": "你的地圖含有額外 25 組神祕木桶",
                                      "Physical Monsters": "你的地圖含有額外 6 群造成物理傷害的怪物",
                                      "Polished Scarab": "最初 3 個被附身的怪物掉落 1 個額外圓滑聖甲蟲",
                                      "Ritual Rerolling": "你地圖中在祭祀神壇重骰恩賜之物，前 1 次免費",
                                      "Rusted Scarab": "最初 3 個被附身的怪物掉落 1 個額外銹蝕聖甲蟲",
                                      "Tormented Graverobber": "最初 3 個被附身的怪物掉落 1 個額外傳奇道具",
                                      #"Ultimatum": "你的地圖含有 1 個最後通牒事件",
                                      "Unique Monsters Drop Corrupted": "傳奇頭目掉落腐化物品",
                                      "Vaal Soul On Kill": "玩家擊殺時額外獲得 1 個瓦爾靈魂"
                                      }
